# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bmonkey/workspace/GFX/gl3cone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bmonkey/workspace/GFX/gl3cone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bmonkey/workspace/GFX/gl3cone/CMakeFiles /home/bmonkey/workspace/GFX/gl3cone/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bmonkey/workspace/GFX/gl3cone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gl3Cone

# Build rule for target.
gl3Cone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gl3Cone
.PHONY : gl3Cone

# fast build rule for target.
gl3Cone/fast:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/build
.PHONY : gl3Cone/fast

src/MediaLayer.o: src/MediaLayer.cpp.o
.PHONY : src/MediaLayer.o

# target to build an object file
src/MediaLayer.cpp.o:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/MediaLayer.cpp.o
.PHONY : src/MediaLayer.cpp.o

src/MediaLayer.i: src/MediaLayer.cpp.i
.PHONY : src/MediaLayer.i

# target to preprocess a source file
src/MediaLayer.cpp.i:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/MediaLayer.cpp.i
.PHONY : src/MediaLayer.cpp.i

src/MediaLayer.s: src/MediaLayer.cpp.s
.PHONY : src/MediaLayer.s

# target to generate assembly for a file
src/MediaLayer.cpp.s:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/MediaLayer.cpp.s
.PHONY : src/MediaLayer.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/RenderEngine.o: src/RenderEngine.cpp.o
.PHONY : src/RenderEngine.o

# target to build an object file
src/RenderEngine.cpp.o:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/RenderEngine.cpp.o
.PHONY : src/RenderEngine.cpp.o

src/RenderEngine.i: src/RenderEngine.cpp.i
.PHONY : src/RenderEngine.i

# target to preprocess a source file
src/RenderEngine.cpp.i:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/RenderEngine.cpp.i
.PHONY : src/RenderEngine.cpp.i

src/RenderEngine.s: src/RenderEngine.cpp.s
.PHONY : src/RenderEngine.s

# target to generate assembly for a file
src/RenderEngine.cpp.s:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/RenderEngine.cpp.s
.PHONY : src/RenderEngine.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/ShaderProgram.o: src/ShaderProgram.cpp.o
.PHONY : src/ShaderProgram.o

# target to build an object file
src/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/ShaderProgram.cpp.o
.PHONY : src/ShaderProgram.cpp.o

src/ShaderProgram.i: src/ShaderProgram.cpp.i
.PHONY : src/ShaderProgram.i

# target to preprocess a source file
src/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/ShaderProgram.cpp.i
.PHONY : src/ShaderProgram.cpp.i

src/ShaderProgram.s: src/ShaderProgram.cpp.s
.PHONY : src/ShaderProgram.s

# target to generate assembly for a file
src/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/ShaderProgram.cpp.s
.PHONY : src/ShaderProgram.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/gl3Cone.dir/build.make CMakeFiles/gl3Cone.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gl3Cone"
	@echo "... rebuild_cache"
	@echo "... src/MediaLayer.o"
	@echo "... src/MediaLayer.i"
	@echo "... src/MediaLayer.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/RenderEngine.o"
	@echo "... src/RenderEngine.i"
	@echo "... src/RenderEngine.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/ShaderProgram.o"
	@echo "... src/ShaderProgram.i"
	@echo "... src/ShaderProgram.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

